"""First set of tables

Revision ID: 8955aaa74f9c
Revises: 
Create Date: 2025-10-31 00:50:30.663591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8955aaa74f9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Pending', name='customerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('fdhs',
    sa.Column('fdh_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('fdh_id')
    )
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_table('splitters',
    sa.Column('splitter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('operational', 'faulty', 'retired', name='splitterstatus'), nullable=False),
    sa.Column('max_ports', sa.Integer(), nullable=False),
    sa.Column('used_ports', sa.Integer(), nullable=False),
    sa.Column('fdh_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fdh_id'], ['fdhs.fdh_id'], ),
    sa.PrimaryKeyConstraint('splitter_id')
    )
    op.create_table('ports',
    sa.Column('port_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('port_status', sa.Enum('free', 'occupied', name='portstatus'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('splitter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['splitter_id'], ['splitters.splitter_id'], ),
    sa.PrimaryKeyConstraint('port_id'),
    sa.UniqueConstraint('port_id')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('ONT', 'Router', name='assettype'), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'available', 'faulty', 'retired', name='assetstatus'), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('assigned_to_customer_id', sa.Integer(), nullable=True),
    sa.Column('stored_at_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['port_id'], ['ports.port_id'], ),
    sa.ForeignKeyConstraint(['stored_at_warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('asset_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('bearing_status', sa.Enum('bearing', 'returned', name='bearingstatus'), nullable=False),
    sa.Column('date_of_issue', sa.DateTime(), nullable=False),
    sa.Column('date_of_return', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_assignments')
    op.drop_table('assets')
    op.drop_table('ports')
    op.drop_table('splitters')
    op.drop_table('warehouses')
    op.drop_table('fdhs')
    op.drop_table('customers')
    # ### end Alembic commands ###
